name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-Github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      uses: actions/checkout@v3
      - name: Create envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students_test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres_sorteador_db:5432/students_test"
          directory: back-end
          file.name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_sorteador_app npm run test